In [20]:
import pandas as pd

df = pd.read_csv("data/bbc_news_train.csv")

df["Category"].value_counts()

Category
sport            346
business         336
politics         274
entertainment    273
tech             261
Name: count, dtype: int64

In [21]:
import pandas as pd

df = pd.read_csv("data/bbc_news_tests.csv")

df["Category"].value_counts()

Category
business         174
sport            165
politics         143
tech             140
entertainment    113
Name: count, dtype: int64

In [86]:
import pandas as pd

df = pd.read_csv("results/enhanced_news.csv")

df["topics"].value_counts()

topics
politics         94
sport            72
business         42
tech             38
entertainment    36
Name: count, dtype: int64

In [87]:
import pandas as pd

df = pd.read_csv("results/enhanced_news.csv")

df["real_topic"].value_counts()

real_topic
politics         87
sport            65
tech             51
business         34
general          27
entertainment    18
Name: count, dtype: int64

In [88]:
df = df[df["real_topic"] != "general"]

from sklearn.metrics import accuracy_score

acc = accuracy_score(df["real_topic"], df["topics"])
print("Accuracy:", acc)

Accuracy: 0.7490196078431373

In [89]:
from sklearn.metrics import classification_report

print(classification_report(df["real_topic"], df["topics"]))

               precision    recall  f1-score   support

     business       0.53      0.59      0.56        34
entertainment       0.52      0.89      0.65        18
     politics       0.80      0.78      0.79        87
        sport       0.97      0.98      0.98        65
         tech       0.66      0.45      0.53        51

     accuracy                           0.75       255
    macro avg       0.69      0.74      0.70       255
 weighted avg       0.76      0.75      0.75       255

In [90]:
df["correct"] = df["real_topic"] == df["topics"]

print(df["correct"].value_counts(normalize=True))

correct
True     0.74902
False    0.25098
Name: proportion, dtype: float64

In [97]:
df[["headline", "orgs", "sentiment", "is_scandal"]].head(20)
df.loc[df["is_scandal"] == True, ["headline", "orgs", "sentiment", "is_scandal"]].head(30)

,headline,orgs,sentiment,is_scandal
42,"'If we sleep, they bite': Rats and weasels inf...","['BBC', 'World Health Organization', 'Hamas', ...",-0.9986,True
247,Global forest loss slows but El Niño fires cou...,"['Copernicus', 'Global Forest Watch', 'BBC', '...",0.9587,True
249,UK's biggest ever environmental pollution clai...,"['BBC', 'Natural England', 'BBC News', 'the Hi...",-0.7417,True
250,'We're living in a shed because of river pollu...,"['BBC', 'Leominster Town Council', 'the High C...",0.9857,True
251,First ever talks to ditch fossil fuels as UN d...,['the Potsdam Institute for Climate Impact Res...,0.9928,True
253,Ban 'forever chemicals' in uniforms and frying...,"['Manchester Met University', 'the Royal Socie...",0.9354,True
256,Butterfly numbers are dropping but here are fi...,"['the University of York', 'BBC', 'Butterfly C...",0.9946,True
260,No ban on over-the-counter pet flea treatments...,"['RAF', 'BBC', 'The Department for Farming and...",-0.9011,True
261,'Mournes could take centuries to recover from ...,"[""Queen's"", 'QUB', 'BBC', 'Rural Affairs', 'Do...",-0.9817,True
266,Sewage and agricultural pollution having 'alar...,"['Extra', 'Moray', 'BBC', 'theGlobal Ecology a...",-0.9265,True
267,'Only so much' voters can worry about - are at...,['the Centre for Climate Change and Social Tra...,0.9957,True
276,Why cheap power could matter more than clean p...,"['Solar', 'BBC', 'Getty Images', 'Tony Blair I...",0.9984,True
280,"COP30: Trump and many leaders are skipping it,...","['BBC', 'Sheffield University', 'Getty Images'...",0.9985,True

In [84]:
df[df["top_10"] == True].head(30)

,id,url,date,headline,body,real_topic,orgs,sentiment,topics,scandal_score,top_10,correct
42,45,https://www.bbc.com/news/articles/c202m54xp0mo...,"Sat, 02 May 2026 05:02:14 GMT","'If we sleep, they bite': Rats and weasels inf...","""We woke up to the sound of her screaming at 2...",politics,"['World Health Organization', 'The Global Sumu...",-0.9986,politics,0.573608,True,True
242,257,https://www.bbc.com/sport/football/articles/cq...,"Tue, 07 Apr 2026 05:06:36 GMT","54 years, 48 leagues, 2,000 grounds - the ulti...","54 years, 48 leagues, 2,000 grounds - the ulti...",sport,"['Hendon', 'the National Football Museum', 'St...",0.9997,sport,0.566133,True,True
247,263,https://www.bbc.com/news/articles/c78q5pygn66o...,"Wed, 29 Apr 2026 13:26:08 GMT",Global forest loss slows but El Niño fires cou...,The loss of tropical rainforests slowed last y...,tech,"['Copernicus', 'the University of Maryland', '...",0.9587,business,0.587649,True,False
250,266,https://www.bbc.com/news/articles/c6244zv02ero...,"Sun, 26 Apr 2026 06:20:08 GMT",'We're living in a shed because of river pollu...,People living and working in Herefordshire say...,tech,"['Herefordshire Council', 'Welsh Water', 'the ...",0.9857,politics,0.579813,True,False
253,269,https://www.bbc.com/news/articles/ckg98q1yx9vo...,"Wed, 22 Apr 2026 23:11:24 GMT",Ban 'forever chemicals' in uniforms and frying...,School uniforms and non-stick pans are some of...,tech,"['Telford', 'the Environment Audit Committee',...",0.9354,politics,0.519745,True,False
259,276,https://www.bbc.com/news/articles/cvgzl329lqlo...,"Sun, 03 May 2026 08:14:19 GMT",Nature haven 'trashed' after four-year wait fo...,"A wildlife haven in Ayrshire has been ""trashed...",tech,"['Chemring Energetics', 'NPL Group', 'the Arde...",0.9955,business,0.550565,True,False
261,278,https://www.bbc.com/news/articles/cevpy8r2e22o...,"Sun, 03 May 2026 05:23:06 GMT",'Mournes could take centuries to recover from ...,Firefighters have once again been battling wil...,tech,"['QUB', 'theAgriculture and Environment', 'Tru...",-0.9817,politics,0.545212,True,False
266,284,https://www.bbc.com/news/articles/cn0pl9j88gno...,"Sat, 02 May 2026 10:46:54 GMT",Sewage and agricultural pollution having 'alar...,Sewage and agricultural pollution in rivers is...,tech,"['Moray', 'theGlobal Ecology and Conservationj...",-0.9265,tech,0.630273,True,True
267,285,https://www.bbc.com/news/articles/c62d4p807lro...,"Thu, 30 Apr 2026 07:46:26 GMT",'Only so much' voters can worry about - are at...,You might expect climate change to be on voter...,tech,"['the Advocacy Academy', 'The Welsh Parliament...",0.9957,politics,0.556079,True,False
276,295,https://www.bbc.com/news/articles/c86ey5n9vx9o...,"Wed, 15 Apr 2026 23:20:22 GMT",Why cheap power could matter more than clean p...,"""I'm an early adopter of new technology,"" says...",tech,"['BBC Your Voice', 'SNP', 'Parliament', 'The C...",0.9984,politics,0.670703,True,False